### ISSUE TITLE
BetaFlight no Gyro

### ISSUE THREAD

**Issue by huseynmammad** [rizacelik/STM32F405RGT6_INAV_Firmware#12]
Merhaba Hocam. Öncelikle proje için teşekkür ederim. Bizim devremiz Betaflight için INAV 7.1'deki devreyle aynı mı? Ayrıca, MPU6050 I2C ile olan devrede Betaflight MPU6050'yi görmüyor. Sanırım MPU9250 ile olan şemayı kullanmam gerek. Bu konuda yardımcı olursanız çok sevinirim. Şimdiden teşekkürler, Hocam.

**Comment by rizacelik** [comment]
Betaflight için maalesef derleme dosyası yok.

**Comment by huseynmammad** [comment]
Hocam son youtube videonuzda BetaFlight kullanıyorsunuz.  Peki sizde hangi devreyle çalışıyor bu? Teşekkürler

**Comment by rizacelik** [comment]
Buraya bakın. https://github.com/rizacelik/STM32F411CEU6_INAV_Firmware

**Comment by ayerko40** [comment]
Hocam çok rica ediyorum mümkünse bunun Betaflight için olanını derleme yapabilir misiniz?

Saygı ve Sevgilerimle
