### ISSUE TITLE
BetaFlight için Derleme Yapabilir misiniz?

### ISSUE THREAD

**Issue by ayerko40** [rizacelik/STM32F405RGT6_INAV_Firmware#13]
Hocam Saygılarımla 
Acaba STM32F405RGT6 için BetaFlight Derlemesi Yapabilir misiniz?

buna çok ihtiyacım var.....   Teşekkürler

**Comment by rizacelik** [comment]
BetaFlight Derlemesi Yapıldı.

**Comment by rizacelik** [comment]
Betaflight için derleme yaptım ama bazı sorunları olduğu bana bildirildi. Bu yüzden kaldırdım. Daha sonra tekrar derleyeceğim. 

Buradaki yazışmaya bakabilirsin. https://github.com/rizacelik/STM32F405RGT6_INAV_Firmware/issues/16

**Comment by ayerko40** [comment]
Çok Teşekkür ediyorum ilginiz için, Sabırsızlıkla bekliyorum 
birde keşke nasıl derleme yapıldığını anlatsaydınız kendimizde uğraşırdık saygılar
    9 Aralık 2024 Pazartesi 20:46:02 GMT+3 tarihinde, Rıza Çelik ***@***.***>şunu yazdı:  
 
 


Betaflight için derleme yaptım ama bazı sorunları olduğu bana bildirildi. Bu yüzden kaldırdım. Daha sonra tekrar derleyeceğim.

Buradaki yazışmaya bakabilirsin. #16
