### ISSUE TITLE
Share please hwdef-bl.dat and hwdef.dat for STM32F405RGT6

### ISSUE THREAD

**Issue by tech0x** [rizacelik/STM32F405RGT6_INAV_Firmware#6]
Hello can You share files for build ardupilot from sources  ?
 hwdef-bl.dat and hwdef.dat

**Comment by rizacelik** [comment]
Your answer is here.
https://github.com/rizacelik/STM32F405RGT6_INAV_Firmware/issues/3#issuecomment-1960122214

**Comment by tech0x** [comment]
Thanks a lot.
