### ISSUE TITLE
Motor 4 is not working (PWM) + support of GY-91

### ISSUE THREAD

**Issue by jct1411** [rizacelik/STM32F405RGT6_INAV_Firmware#9]
I setup some config with WeAct Studio STM32F405RGT6 Board but motor 4 (PWM) does not work.  I tried with 2 boards and also probed the signal with an oscilloscope but not signal is shown.  

It would also be great if GY-91 could be supported since barometer is not recognized when cabling with SPI.  

Thanks

**Comment by mursa1en** [comment]
I am also facing the same problem on the motor 4. Were you able to resolve it?

**Comment by mursa1en** [comment]
> I setup some config with WeAct Studio STM32F405RGT6 Board but motor 4 (PWM) does not work.  I tried with 2 boards and also probed the signal with an oscilloscope but not signal is shown.  
> 
> It would also be great if GY-91 could be supported since barometer is not recognized when cabling with SPI.  
> 
> Thanks

Which firmware did you use? Motor 4 is working fine on the arducopter firmware.

**Comment by mursa1en** [comment]
Motor 4 is also working on inav 6.1.1

**Comment by jct1411** [comment]
I used Inav 7.0.0.  I did not try with firmware 6.1.1

**Comment by jct1411** [comment]
I was not able to resolve the problem but it seems to be related to some invalid timer which is assigned to the pin corresponding to motor 4.  Not possible apparently to solve such issue via CLI in Inav and some rebuild is probably mandatory.

**Comment by shrinibas7** [comment]
> I used Inav 7.0.0. I did not try with firmware 6.1.1

Use pb1 as motor 4 in inav 7.0.0
